version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - 9200:9200
      - 9300:9300

  dejavu:
    image: appbaseio/dejavu
    ports:
      - 1358:1358
